[chore] bump versions
pulumi/pulumi-tf-provider-boilerplate pull request #67
Opened 2022-04-27 01:09 UTC by guineveresaenger

2022-04-28 22:47 UTC, stack72 requested changes
we need to change the sdk/go.mod as well

2022-04-29 17:25 UTC, guineveresaenger commented
I verified these updates by generating a third party provider using Go 1.17,  Pulumi v3.30.0, and Terraform bridge v3.21.0.

Also stumbled across a documentation lapse with a fix in https://github.com/pulumi/pulumi-terraform-bridge/pull/513, and altered the instructions for ResourceInfo accordingly.

2022-04-29 17:28 UTC, guineveresaenger commented
part of https://github.com/pulumi/home/issues/1997

2022-04-29 20:29 UTC, stack72 approved these changes

2022-04-29 20:39 UTC, merged